plugins {
    id 'org.jetbrains.kotlin.jvm'
}

def kotlinVersion = providers.gradleProperty("kotlinVersion").get()

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation project(':plugin-annotations')
    implementation "org.jetbrains.kotlin:kotlin-compiler-embeddable:${kotlinVersion}"
}
